In [1]:
import numpy as np

In [7]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
np.place(arr, arr>2, [44,55,88])

In [9]:
arr

array([[ 0,  1,  2],
       [44, 55, 88]])

In [12]:
L = 400
xc = np.random.uniform(0,L, size = 20)

In [13]:
xc

array([379.4724178 , 393.26691085,  76.15569715, 165.03676891,
       252.32930525, 137.23670685, 335.04076503, 249.30189745,
       314.54680704, 386.95858203,  29.1610271 , 375.06700747,
       386.36932974, 263.36661734,  84.2022784 , 226.4035951 ,
       206.2109351 ,  45.82170191, 270.04588508, 164.18827576])

In [14]:
nx = 4

In [18]:
indice_x = np.int32(np.ceil(xc *(nx/L)))

In [19]:
indice_x

array([4, 4, 1, 2, 3, 2, 4, 3, 4, 4, 1, 4, 4, 3, 1, 3, 3, 1, 3, 2],
      dtype=int32)